FROM node:16-alpine AS build_stage
WORKDIR /
COPY package*.json ./app
RUN npm install
COPY . .
RUN npm run build
RUN npm prune --production

FROM node:16-alpine 
WORKDIR /
RUN npm install --global serve
COPY --from=build_stage  /app ./build
COPY --from=build_stage  /app ./node_modules
CMD ["serve", "-s", "build"]
