name: Create PR on Issue Creation
on:
  issues:
    types: [opened]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Automatically create PR on issue creation'
        branch: 'feature/${{ github.event.issue.number }}'
        title: 'Feature/${{ github.event.issue.number }}'
        body: |
          This PR has been automatically created to address issue #${{ github.event.issue.number }}.

          Please review and merge as appropriate.
