name: Setup Branch on Issue Creation
on:
  issues:
    types: [opened]

jobs:
  setup-branch:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Create branch
      run: |
        branch_name="issue-${{ github.event.issue.number }}"
        git checkout -b "$branch_name"
        git push -u origin "$branch_name"

    - name: Add branch reference to issue
      uses: peter-evans/add-issue-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        message: |
          A branch has been created for this issue.

          Branch: ${{ github.event.issue.number }}

          Please review and provide updates as necessary.